/* 卡片驗證結果。由 test_tools/verify_pairs.js（引擎層窮舉）與介面實測合併產生，不要手改。
   singles[id].okAt  這張卡單獨玩時幾人玩得動（引擎層）
   mates[id]         引擎層驗過可以搭的卡
   uiSingles         真的走過介面、三場都打到分出勝負的卡（畫面上標「已實測」）
   uiStats[id]       介面實測的通過場次／總場次
   quirky            我們測到「怪怪的」那幾張。🔴 只記 id 不記症狀——
                     寫出症狀就等於把答案給學生，而自己找出哪裡怪正是這週要練的 playtesting。
   🔴 沒進 uiSingles 不代表不能玩——楊老師 2026-09-23 定案：40 張全部開放當單張，
      玩到怪怪的就回報，那本身就是 playtesting 練習。只有「兩張組合」才限定驗證過的。 */
window.SF3K_VERIFIED = {
 "singles": {
  "chips_1": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "chips_20": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "solo_hard": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "team_hard": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "team_mob": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "team_square": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "team_diminish": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "team_penalty": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "defend_strong": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "defend_weak": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "no_turtle": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "no_repeat": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "decay": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "round_cap": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "last_one": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "anonymous": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "fog": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "timed_talk": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "comeback": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "redirect": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "guard": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "vampire": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "drain": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "draw_target": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "seat_ring": {
   "okAt": [
    4,
    5,
    6
   ],
   "bad": []
  },
  "ghost": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "jury": {
   "okAt": [
    4,
    5,
    6
   ],
   "bad": []
  },
  "elements": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "events": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "theme_mol": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "theme_charm": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "theme_money": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "theme_office": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "blitz": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "whisper": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "roles": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "range2": {
   "okAt": [
    6
   ],
   "bad": []
  },
  "factions": {
   "okAt": [
    4,
    5,
    6
   ],
   "bad": []
  },
  "items": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  },
  "stack": {
   "okAt": [
    3,
    4,
    5,
    6
   ],
   "bad": []
  }
 },
 "mates": {
  "chips_1": [
   "solo_hard",
   "team_hard",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_weak",
   "no_repeat",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "roles",
   "factions",
   "items",
   "stack"
  ],
  "chips_20": [
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "roles",
   "range2",
   "factions",
   "items",
   "stack"
  ],
  "solo_hard": [
   "chips_1",
   "chips_20",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "roles",
   "range2",
   "factions",
   "items",
   "stack"
  ],
  "team_hard": [
   "chips_1",
   "chips_20",
   "solo_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "roles",
   "range2",
   "factions",
   "items",
   "stack"
  ],
  "team_mob": [
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "roles",
   "range2",
   "factions",
   "items",
   "stack"
  ],
  "team_square": [
   "chips_1",
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "roles",
   "range2",
   "factions",
   "items",
   "stack"
  ],
  "team_diminish": [
   "chips_1",
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "roles",
   "range2",
   "factions",
   "items",
   "stack"
  ],
  "team_penalty": [
   "chips_1",
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "roles",
   "range2",
   "factions",
   "items",
   "stack"
  ],
  "defend_strong": [
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "roles",
   "range2",
   "factions",
   "items",
   "stack"
  ],
  "defend_weak": [
   "chips_1",
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "roles",
   "range2",
   "factions",
   "items",
   "stack"
  ],
  "no_turtle": [
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "roles",
   "range2",
   "factions",
   "items",
   "stack"
  ],
  "no_repeat": [
   "chips_1",
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "roles",
   "range2",
   "factions",
   "items",
   "stack"
  ],
  "decay": [
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "roles",
   "range2",
   "factions",
   "items",
   "stack"
  ],
  "round_cap": [
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "roles",
   "factions",
   "items",
   "stack"
  ],
  "last_one": [
   "chips_1",
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "roles",
   "range2",
   "factions",
   "items",
   "stack"
  ],
  "anonymous": [
   "chips_1",
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "roles",
   "range2",
   "factions",
   "items",
   "stack"
  ],
  "fog": [
   "chips_1",
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "roles",
   "range2",
   "factions",
   "items",
   "stack"
  ],
  "timed_talk": [
   "chips_1",
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "roles",
   "range2",
   "factions",
   "items",
   "stack"
  ],
  "comeback": [
   "chips_1",
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "roles",
   "range2",
   "factions",
   "items",
   "stack"
  ],
  "redirect": [
   "chips_1",
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "roles",
   "range2",
   "factions",
   "items",
   "stack"
  ],
  "guard": [
   "chips_1",
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "roles",
   "range2",
   "factions",
   "items",
   "stack"
  ],
  "vampire": [
   "chips_1",
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "drain",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "roles",
   "range2",
   "factions",
   "items",
   "stack"
  ],
  "drain": [
   "chips_1",
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "roles",
   "range2",
   "factions",
   "items",
   "stack"
  ],
  "draw_target": [
   "chips_1",
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "drain",
   "ghost",
   "jury",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "roles",
   "factions",
   "items",
   "stack"
  ],
  "seat_ring": [
   "chips_1",
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "ghost",
   "jury",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "roles",
   "factions",
   "items",
   "stack"
  ],
  "ghost": [
   "chips_1",
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "roles",
   "range2",
   "factions",
   "items",
   "stack"
  ],
  "jury": [
   "chips_1",
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "roles",
   "range2",
   "factions",
   "items",
   "stack"
  ],
  "elements": [
   "chips_1",
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "roles",
   "range2",
   "factions",
   "items",
   "stack"
  ],
  "events": [
   "chips_1",
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "roles",
   "range2",
   "factions",
   "items",
   "stack"
  ],
  "theme_mol": [
   "chips_1",
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "blitz",
   "whisper",
   "roles",
   "range2",
   "factions",
   "items",
   "stack"
  ],
  "theme_charm": [
   "chips_1",
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "blitz",
   "whisper",
   "roles",
   "range2",
   "factions",
   "items",
   "stack"
  ],
  "theme_money": [
   "chips_1",
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "blitz",
   "whisper",
   "roles",
   "range2",
   "factions",
   "items",
   "stack"
  ],
  "theme_office": [
   "chips_1",
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "blitz",
   "whisper",
   "roles",
   "range2",
   "factions",
   "items",
   "stack"
  ],
  "blitz": [
   "chips_1",
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "whisper",
   "roles",
   "range2",
   "factions",
   "items",
   "stack"
  ],
  "whisper": [
   "chips_1",
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "roles",
   "range2",
   "factions",
   "items",
   "stack"
  ],
  "roles": [
   "chips_1",
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "range2",
   "factions",
   "stack"
  ],
  "range2": [
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "ghost",
   "jury",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "roles",
   "factions",
   "items",
   "stack"
  ],
  "factions": [
   "chips_1",
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "roles",
   "range2",
   "items",
   "stack"
  ],
  "items": [
   "chips_1",
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "range2",
   "factions",
   "stack"
  ],
  "stack": [
   "chips_1",
   "chips_20",
   "solo_hard",
   "team_hard",
   "team_mob",
   "team_square",
   "team_diminish",
   "team_penalty",
   "defend_strong",
   "defend_weak",
   "no_turtle",
   "no_repeat",
   "decay",
   "round_cap",
   "last_one",
   "anonymous",
   "fog",
   "timed_talk",
   "comeback",
   "redirect",
   "guard",
   "vampire",
   "drain",
   "draw_target",
   "seat_ring",
   "ghost",
   "jury",
   "elements",
   "events",
   "theme_mol",
   "theme_charm",
   "theme_money",
   "theme_office",
   "blitz",
   "whisper",
   "roles",
   "range2",
   "factions",
   "items"
  ]
 },
 "uiSingles": [
  "anonymous",
  "blitz",
  "chips_1",
  "chips_20",
  "comeback",
  "decay",
  "defend_strong",
  "defend_weak",
  "drain",
  "elements",
  "events",
  "fog",
  "ghost",
  "guard",
  "items",
  "last_one",
  "no_repeat",
  "no_turtle",
  "redirect",
  "roles",
  "round_cap",
  "seat_ring",
  "solo_hard",
  "stack",
  "team_diminish",
  "team_hard",
  "team_mob",
  "team_penalty",
  "team_square",
  "theme_charm",
  "theme_mol",
  "theme_money",
  "theme_office",
  "timed_talk",
  "vampire",
  "whisper"
 ],
 "uiStats": {
  "anonymous": {
   "ok": 3,
   "n": 3
  },
  "blitz": {
   "ok": 3,
   "n": 3
  },
  "chips_1": {
   "ok": 3,
   "n": 3
  },
  "chips_20": {
   "ok": 3,
   "n": 3
  },
  "comeback": {
   "ok": 3,
   "n": 3
  },
  "decay": {
   "ok": 3,
   "n": 3
  },
  "defend_strong": {
   "ok": 3,
   "n": 3
  },
  "defend_weak": {
   "ok": 3,
   "n": 3
  },
  "drain": {
   "ok": 3,
   "n": 3
  },
  "draw_target": {
   "ok": 0,
   "n": 3
  },
  "elements": {
   "ok": 3,
   "n": 3
  },
  "events": {
   "ok": 0,
   "n": 3
  },
  "factions": {
   "ok": 0,
   "n": 3
  },
  "fog": {
   "ok": 1,
   "n": 6
  },
  "ghost": {
   "ok": 3,
   "n": 3
  },
  "guard": {
   "ok": 0,
   "n": 6
  },
  "items": {
   "ok": 3,
   "n": 3
  },
  "jury": {
   "ok": 0,
   "n": 3
  },
  "last_one": {
   "ok": 3,
   "n": 3
  },
  "no_repeat": {
   "ok": 3,
   "n": 6
  },
  "no_turtle": {
   "ok": 3,
   "n": 3
  },
  "range2": {
   "ok": 0,
   "n": 3
  },
  "redirect": {
   "ok": 3,
   "n": 3
  },
  "roles": {
   "ok": 3,
   "n": 3
  },
  "round_cap": {
   "ok": 3,
   "n": 3
  },
  "seat_ring": {
   "ok": 0,
   "n": 6
  },
  "solo_hard": {
   "ok": 3,
   "n": 3
  },
  "stack": {
   "ok": 3,
   "n": 3
  },
  "team_diminish": {
   "ok": 3,
   "n": 3
  },
  "team_hard": {
   "ok": 3,
   "n": 3
  },
  "team_mob": {
   "ok": 3,
   "n": 3
  },
  "team_penalty": {
   "ok": 3,
   "n": 3
  },
  "team_square": {
   "ok": 3,
   "n": 3
  },
  "theme_charm": {
   "ok": 3,
   "n": 3
  },
  "theme_mol": {
   "ok": 3,
   "n": 3
  },
  "theme_money": {
   "ok": 3,
   "n": 3
  },
  "theme_office": {
   "ok": 0,
   "n": 3
  },
  "timed_talk": {
   "ok": 3,
   "n": 3
  },
  "vampire": {
   "ok": 3,
   "n": 3
  },
  "whisper": {
   "ok": 3,
   "n": 3
  }
 },
 "quirky": [
  "draw_target"
 ],
 "needs4p": [
  "factions",
  "jury",
  "range2",
  "seat_ring"
 ],
 "roundCapPending": [
  "fog",
  "guard",
  "theme_office"
 ],
 "note_20260923": "theme_office 是純換皮（patch 只有 theme），機制等同原版，卻三場都打不完 30 回合 ⇒ roundCapPending 這三張不算卡片問題，是測試員隨機出牌不會協調 TEAM。needs4p 那四張是遊戲自己的人數驗證擋下來的（正確行為），要 4 個測試視窗才測得到。 ⚠ 先前 quirky 寫成 seat_right，那個 id 在卡池裡不存在（真正的是 draw_target）⇒ 那個 ⚠ 標記從來沒有真的顯示過。憑記憶寫 id 不對資料，跟 QR 選擇器事故同一型。",
 "needs4pVerified": [
  "seat_ring"
 ],
 "uiPairs": {
  "anonymous": [
   "blitz",
   "chips_1",
   "comeback",
   "decay",
   "defend_weak",
   "drain",
   "elements",
   "events",
   "fog",
   "ghost",
   "guard",
   "items",
   "no_repeat",
   "redirect",
   "roles",
   "round_cap",
   "stack",
   "stu:10:-P2B0dmHkunxunTPekwO",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:13:-P2B5_V4r6MtzzRJ9NLe",
   "stu:18:-P2BBk1VRoxDEwd2tY5d",
   "stu:1:-P2B8ecngBuFVPbiwyEh",
   "stu:21:-P2AzhE_4Gm3CrTJ9N81",
   "stu:27:-P2B92Hu_rCT_8m3mrHF",
   "stu:29:-P2B97a2KWneHHRcSjGf",
   "stu:31:-P2B09GdjKzY084CM1yB",
   "stu:36:-P2B5Ooof8XaHcxcxOZT",
   "stu:37:-P2B3F63oAZMByik5EA-",
   "stu:3:-P2B-KB62XfTsw8GngWS",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "stu:47:-P2AzXCJUoZBWXYA1c2o",
   "stu:48:-P2BCDcUreQ4GJTnNPQF",
   "stu:50:-P2B4q3NOzFDEOb3W1vc",
   "stu:51:-P2B3QmzlTbuHdXrbzLy",
   "stu:64:-P2B0gVaTthJtyYsBrkG",
   "stu:7:-P2B37zH4wqV3dVP_NUJ",
   "team_diminish",
   "team_penalty",
   "team_square",
   "timed_talk",
   "vampire",
   "whisper"
  ],
  "blitz": [
   "anonymous",
   "chips_1",
   "chips_20",
   "comeback",
   "drain",
   "elements",
   "events",
   "fog",
   "ghost",
   "guard",
   "items",
   "no_repeat",
   "redirect",
   "roles",
   "round_cap",
   "stack",
   "stu:10:-P2B0dmHkunxunTPekwO",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:13:-P2B5_V4r6MtzzRJ9NLe",
   "stu:18:-P2BBk1VRoxDEwd2tY5d",
   "stu:1:-P2B8ecngBuFVPbiwyEh",
   "stu:21:-P2AzhE_4Gm3CrTJ9N81",
   "stu:27:-P2B92Hu_rCT_8m3mrHF",
   "stu:29:-P2B97a2KWneHHRcSjGf",
   "stu:31:-P2B09GdjKzY084CM1yB",
   "stu:36:-P2B5Ooof8XaHcxcxOZT",
   "stu:37:-P2B3F63oAZMByik5EA-",
   "stu:3:-P2B-KB62XfTsw8GngWS",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "stu:47:-P2AzXCJUoZBWXYA1c2o",
   "stu:48:-P2BCDcUreQ4GJTnNPQF",
   "stu:50:-P2B4q3NOzFDEOb3W1vc",
   "stu:51:-P2B3QmzlTbuHdXrbzLy",
   "stu:64:-P2B0gVaTthJtyYsBrkG",
   "stu:7:-P2B37zH4wqV3dVP_NUJ",
   "team_diminish",
   "team_square",
   "timed_talk",
   "vampire",
   "whisper"
  ],
  "chips_1": [
   "anonymous",
   "blitz",
   "comeback",
   "defend_weak",
   "drain",
   "elements",
   "events",
   "fog",
   "ghost",
   "guard",
   "items",
   "last_one",
   "no_repeat",
   "redirect",
   "roles",
   "solo_hard",
   "stack",
   "stu:10:-P2B0dmHkunxunTPekwO",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:13:-P2B5_V4r6MtzzRJ9NLe",
   "stu:14:-P2B9I9gGwDYhIvnvASd",
   "stu:18:-P2BBk1VRoxDEwd2tY5d",
   "stu:1:-P2B8ecngBuFVPbiwyEh",
   "stu:21:-P2AzhE_4Gm3CrTJ9N81",
   "stu:22:-P2BBWIMu9k_0mDkNVj6",
   "stu:25:-P2B6EdwzasZjsIddBlG",
   "stu:27:-P2B92Hu_rCT_8m3mrHF",
   "stu:29:-P2B97a2KWneHHRcSjGf",
   "stu:30:-P2B9Cd0YWJRZvb9laMY",
   "stu:31:-P2B09GdjKzY084CM1yB",
   "stu:33:-P2B2HlMzGCI9t9BOipg",
   "stu:35:-P2AzDc0OegT_-bshhCZ",
   "stu:36:-P2B5Ooof8XaHcxcxOZT",
   "stu:37:-P2B3F63oAZMByik5EA-",
   "stu:40:-P2B7koBRf7jrlIB4RtH",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:43:-P2B0Aei9XIYF0BSxi8e",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "stu:46:-P2AzLdZx-Nd6vHLsyZH",
   "stu:48:-P2BCDcUreQ4GJTnNPQF",
   "stu:50:-P2B4q3NOzFDEOb3W1vc",
   "stu:51:-P2B3QmzlTbuHdXrbzLy",
   "stu:53:-P2BAjffQXdJaIE5d2dg",
   "stu:54:-P2B65xZ3SrtmoqcxJ3n",
   "stu:5:-P2B8S5V5cot0tguquHo",
   "stu:61:-P2BG3Pq0XolXI-rO6rU",
   "stu:64:-P2B0gVaTthJtyYsBrkG",
   "stu:6:-P2B5SZ7379YyLXx41-8",
   "stu:7:-P2B37zH4wqV3dVP_NUJ",
   "team_diminish",
   "team_hard",
   "team_penalty",
   "team_square",
   "theme_charm",
   "theme_mol",
   "theme_money",
   "theme_office",
   "timed_talk",
   "whisper"
  ],
  "chips_20": [
   "blitz",
   "drain",
   "fog",
   "last_one",
   "round_cap",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:14:-P2B9I9gGwDYhIvnvASd",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "stu:5:-P2B8S5V5cot0tguquHo",
   "timed_talk",
   "whisper"
  ],
  "comeback": [
   "anonymous",
   "blitz",
   "chips_1",
   "fog",
   "round_cap",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "timed_talk",
   "whisper"
  ],
  "decay": [
   "anonymous",
   "defend_weak",
   "fog",
   "ghost",
   "last_one",
   "stack",
   "theme_mol",
   "whisper"
  ],
  "defend_strong": [
   "fog",
   "round_cap"
  ],
  "defend_weak": [
   "anonymous",
   "chips_1",
   "decay",
   "fog",
   "ghost",
   "round_cap",
   "stack",
   "theme_mol",
   "whisper"
  ],
  "drain": [
   "anonymous",
   "blitz",
   "chips_1",
   "chips_20",
   "fog",
   "round_cap",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "timed_talk",
   "whisper"
  ],
  "elements": [
   "anonymous",
   "blitz",
   "chips_1",
   "fog",
   "round_cap",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:25:-P2B6EdwzasZjsIddBlG",
   "stu:40:-P2B7koBRf7jrlIB4RtH",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:43:-P2B0Aei9XIYF0BSxi8e",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "timed_talk",
   "whisper"
  ],
  "events": [
   "anonymous",
   "blitz",
   "chips_1",
   "round_cap",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "timed_talk",
   "whisper"
  ],
  "fog": [
   "anonymous",
   "blitz",
   "chips_1",
   "chips_20",
   "comeback",
   "decay",
   "defend_strong",
   "defend_weak",
   "drain",
   "elements",
   "ghost",
   "guard",
   "items",
   "last_one",
   "no_repeat",
   "no_turtle",
   "redirect",
   "round_cap",
   "solo_hard",
   "stack",
   "stu:10:-P2B0dmHkunxunTPekwO",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:13:-P2B5_V4r6MtzzRJ9NLe",
   "stu:14:-P2B9I9gGwDYhIvnvASd",
   "stu:18:-P2BBk1VRoxDEwd2tY5d",
   "stu:19:-P2BB0F1WYIY-WPeM7W7",
   "stu:1:-P2B8ecngBuFVPbiwyEh",
   "stu:21:-P2AzhE_4Gm3CrTJ9N81",
   "stu:22:-P2BBWIMu9k_0mDkNVj6",
   "stu:25:-P2B6EdwzasZjsIddBlG",
   "stu:27:-P2B92Hu_rCT_8m3mrHF",
   "stu:30:-P2B9Cd0YWJRZvb9laMY",
   "stu:31:-P2B09GdjKzY084CM1yB",
   "stu:33:-P2B2HlMzGCI9t9BOipg",
   "stu:35:-P2AzDc0OegT_-bshhCZ",
   "stu:36:-P2B5Ooof8XaHcxcxOZT",
   "stu:37:-P2B3F63oAZMByik5EA-",
   "stu:40:-P2B7koBRf7jrlIB4RtH",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:43:-P2B0Aei9XIYF0BSxi8e",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "stu:46:-P2AzLdZx-Nd6vHLsyZH",
   "stu:47:-P2AzXCJUoZBWXYA1c2o",
   "stu:48:-P2BCDcUreQ4GJTnNPQF",
   "stu:49:-P2B09-n5zf1Wudi7G24",
   "stu:50:-P2B4q3NOzFDEOb3W1vc",
   "stu:51:-P2B3QmzlTbuHdXrbzLy",
   "stu:52:-P2B2keGRds5euNq7jDt",
   "stu:53:-P2BAjffQXdJaIE5d2dg",
   "stu:54:-P2B65xZ3SrtmoqcxJ3n",
   "stu:5:-P2B8S5V5cot0tguquHo",
   "stu:61:-P2BG3Pq0XolXI-rO6rU",
   "stu:63:-P2B3clYH5CtTdSgk0DT",
   "stu:64:-P2B0gVaTthJtyYsBrkG",
   "stu:6:-P2B5SZ7379YyLXx41-8",
   "stu:7:-P2B37zH4wqV3dVP_NUJ",
   "team_diminish",
   "team_hard",
   "team_mob",
   "team_penalty",
   "team_square",
   "theme_charm",
   "theme_mol",
   "theme_money",
   "theme_office",
   "timed_talk",
   "vampire",
   "whisper"
  ],
  "ghost": [
   "anonymous",
   "blitz",
   "chips_1",
   "decay",
   "defend_weak",
   "fog",
   "round_cap",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "team_penalty",
   "timed_talk",
   "whisper"
  ],
  "guard": [
   "anonymous",
   "blitz",
   "chips_1",
   "fog",
   "round_cap",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "timed_talk",
   "whisper"
  ],
  "items": [
   "anonymous",
   "blitz",
   "chips_1",
   "fog",
   "round_cap",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "timed_talk",
   "whisper"
  ],
  "last_one": [
   "chips_1",
   "chips_20",
   "decay",
   "fog",
   "round_cap"
  ],
  "no_repeat": [
   "anonymous",
   "blitz",
   "chips_1",
   "fog",
   "round_cap",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "timed_talk",
   "whisper"
  ],
  "no_turtle": [
   "fog"
  ],
  "redirect": [
   "anonymous",
   "blitz",
   "chips_1",
   "fog",
   "round_cap",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "timed_talk",
   "whisper"
  ],
  "roles": [
   "anonymous",
   "blitz",
   "chips_1",
   "round_cap",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:44:-P2B8HCd2cKi1btq7y7I"
  ],
  "round_cap": [
   "anonymous",
   "blitz",
   "chips_20",
   "comeback",
   "defend_strong",
   "defend_weak",
   "drain",
   "elements",
   "events",
   "fog",
   "ghost",
   "guard",
   "items",
   "last_one",
   "no_repeat",
   "redirect",
   "roles",
   "stack",
   "stu:10:-P2B0dmHkunxunTPekwO",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:13:-P2B5_V4r6MtzzRJ9NLe",
   "stu:14:-P2B9I9gGwDYhIvnvASd",
   "stu:18:-P2BBk1VRoxDEwd2tY5d",
   "stu:1:-P2B8ecngBuFVPbiwyEh",
   "stu:21:-P2AzhE_4Gm3CrTJ9N81",
   "stu:27:-P2B92Hu_rCT_8m3mrHF",
   "stu:29:-P2B97a2KWneHHRcSjGf",
   "stu:30:-P2B9Cd0YWJRZvb9laMY",
   "stu:31:-P2B09GdjKzY084CM1yB",
   "stu:36:-P2B5Ooof8XaHcxcxOZT",
   "stu:37:-P2B3F63oAZMByik5EA-",
   "stu:3:-P2B-KB62XfTsw8GngWS",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "stu:46:-P2AzLdZx-Nd6vHLsyZH",
   "stu:47:-P2AzXCJUoZBWXYA1c2o",
   "stu:48:-P2BCDcUreQ4GJTnNPQF",
   "stu:49:-P2B09-n5zf1Wudi7G24",
   "stu:50:-P2B4q3NOzFDEOb3W1vc",
   "stu:51:-P2B3QmzlTbuHdXrbzLy",
   "stu:54:-P2B65xZ3SrtmoqcxJ3n",
   "stu:5:-P2B8S5V5cot0tguquHo",
   "stu:63:-P2B3clYH5CtTdSgk0DT",
   "stu:64:-P2B0gVaTthJtyYsBrkG",
   "stu:7:-P2B37zH4wqV3dVP_NUJ",
   "team_diminish",
   "team_hard",
   "team_penalty",
   "team_square",
   "theme_charm",
   "theme_mol",
   "theme_money",
   "theme_office",
   "vampire",
   "whisper"
  ],
  "solo_hard": [
   "chips_1",
   "fog"
  ],
  "stack": [
   "anonymous",
   "blitz",
   "chips_1",
   "decay",
   "defend_weak",
   "fog",
   "round_cap",
   "team_penalty"
  ],
  "stu:10:-P2B0dmHkunxunTPekwO": [
   "anonymous",
   "blitz",
   "chips_1",
   "fog",
   "round_cap",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "whisper"
  ],
  "stu:11:-P2BAe3ohZSRO5b-VhPv": [
   "anonymous",
   "chips_1",
   "chips_20",
   "comeback",
   "drain",
   "elements",
   "events",
   "fog",
   "ghost",
   "guard",
   "items",
   "no_repeat",
   "redirect",
   "roles",
   "round_cap",
   "stu:10:-P2B0dmHkunxunTPekwO",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:13:-P2B5_V4r6MtzzRJ9NLe",
   "stu:18:-P2BBk1VRoxDEwd2tY5d",
   "stu:1:-P2B8ecngBuFVPbiwyEh",
   "stu:21:-P2AzhE_4Gm3CrTJ9N81",
   "stu:27:-P2B92Hu_rCT_8m3mrHF",
   "stu:29:-P2B97a2KWneHHRcSjGf",
   "stu:31:-P2B09GdjKzY084CM1yB",
   "stu:36:-P2B5Ooof8XaHcxcxOZT",
   "stu:37:-P2B3F63oAZMByik5EA-",
   "stu:3:-P2B-KB62XfTsw8GngWS",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "stu:47:-P2AzXCJUoZBWXYA1c2o",
   "stu:48:-P2BCDcUreQ4GJTnNPQF",
   "stu:50:-P2B4q3NOzFDEOb3W1vc",
   "stu:51:-P2B3QmzlTbuHdXrbzLy",
   "stu:64:-P2B0gVaTthJtyYsBrkG",
   "stu:7:-P2B37zH4wqV3dVP_NUJ",
   "team_diminish",
   "vampire",
   "whisper"
  ],
  "stu:12:-P2BAU97nHwtxxKcdNgU": [
   "anonymous",
   "blitz",
   "chips_1",
   "chips_20",
   "comeback",
   "drain",
   "events",
   "fog",
   "ghost",
   "guard",
   "items",
   "no_repeat",
   "redirect",
   "roles",
   "round_cap",
   "stu:10:-P2B0dmHkunxunTPekwO",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:13:-P2B5_V4r6MtzzRJ9NLe",
   "stu:18:-P2BBk1VRoxDEwd2tY5d",
   "stu:1:-P2B8ecngBuFVPbiwyEh",
   "stu:21:-P2AzhE_4Gm3CrTJ9N81",
   "stu:27:-P2B92Hu_rCT_8m3mrHF",
   "stu:29:-P2B97a2KWneHHRcSjGf",
   "stu:31:-P2B09GdjKzY084CM1yB",
   "stu:36:-P2B5Ooof8XaHcxcxOZT",
   "stu:37:-P2B3F63oAZMByik5EA-",
   "stu:3:-P2B-KB62XfTsw8GngWS",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:47:-P2AzXCJUoZBWXYA1c2o",
   "stu:48:-P2BCDcUreQ4GJTnNPQF",
   "stu:50:-P2B4q3NOzFDEOb3W1vc",
   "stu:51:-P2B3QmzlTbuHdXrbzLy",
   "stu:64:-P2B0gVaTthJtyYsBrkG",
   "stu:7:-P2B37zH4wqV3dVP_NUJ",
   "team_diminish",
   "vampire",
   "whisper"
  ],
  "stu:13:-P2B5_V4r6MtzzRJ9NLe": [
   "anonymous",
   "blitz",
   "chips_1",
   "fog",
   "round_cap",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "whisper"
  ],
  "stu:14:-P2B9I9gGwDYhIvnvASd": [
   "chips_1",
   "chips_20",
   "fog",
   "round_cap"
  ],
  "stu:18:-P2BBk1VRoxDEwd2tY5d": [
   "anonymous",
   "blitz",
   "chips_1",
   "fog",
   "round_cap",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "whisper"
  ],
  "stu:19:-P2BB0F1WYIY-WPeM7W7": [
   "fog"
  ],
  "stu:1:-P2B8ecngBuFVPbiwyEh": [
   "anonymous",
   "blitz",
   "chips_1",
   "fog",
   "round_cap",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:44:-P2B8HCd2cKi1btq7y7I"
  ],
  "stu:21:-P2AzhE_4Gm3CrTJ9N81": [
   "anonymous",
   "blitz",
   "chips_1",
   "fog",
   "round_cap",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "whisper"
  ],
  "stu:22:-P2BBWIMu9k_0mDkNVj6": [
   "chips_1",
   "fog"
  ],
  "stu:25:-P2B6EdwzasZjsIddBlG": [
   "chips_1",
   "elements",
   "fog"
  ],
  "stu:27:-P2B92Hu_rCT_8m3mrHF": [
   "anonymous",
   "blitz",
   "chips_1",
   "fog",
   "round_cap",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "whisper"
  ],
  "stu:29:-P2B97a2KWneHHRcSjGf": [
   "anonymous",
   "blitz",
   "chips_1",
   "round_cap",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "whisper"
  ],
  "stu:30:-P2B9Cd0YWJRZvb9laMY": [
   "chips_1",
   "fog",
   "round_cap"
  ],
  "stu:31:-P2B09GdjKzY084CM1yB": [
   "anonymous",
   "blitz",
   "chips_1",
   "fog",
   "round_cap",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "whisper"
  ],
  "stu:33:-P2B2HlMzGCI9t9BOipg": [
   "chips_1",
   "fog"
  ],
  "stu:35:-P2AzDc0OegT_-bshhCZ": [
   "chips_1",
   "fog"
  ],
  "stu:36:-P2B5Ooof8XaHcxcxOZT": [
   "anonymous",
   "blitz",
   "chips_1",
   "fog",
   "round_cap",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "whisper"
  ],
  "stu:37:-P2B3F63oAZMByik5EA-": [
   "anonymous",
   "blitz",
   "chips_1",
   "fog",
   "round_cap",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "whisper"
  ],
  "stu:3:-P2B-KB62XfTsw8GngWS": [
   "anonymous",
   "blitz",
   "round_cap",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "timed_talk",
   "whisper"
  ],
  "stu:40:-P2B7koBRf7jrlIB4RtH": [
   "chips_1",
   "elements",
   "fog"
  ],
  "stu:41:-P2B2G8cXTL02fSJhM3t": [
   "anonymous",
   "chips_1",
   "chips_20",
   "comeback",
   "drain",
   "elements",
   "events",
   "fog",
   "ghost",
   "guard",
   "items",
   "no_repeat",
   "redirect",
   "roles",
   "round_cap",
   "stu:10:-P2B0dmHkunxunTPekwO",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:13:-P2B5_V4r6MtzzRJ9NLe",
   "stu:18:-P2BBk1VRoxDEwd2tY5d",
   "stu:1:-P2B8ecngBuFVPbiwyEh",
   "stu:21:-P2AzhE_4Gm3CrTJ9N81",
   "stu:27:-P2B92Hu_rCT_8m3mrHF",
   "stu:29:-P2B97a2KWneHHRcSjGf",
   "stu:31:-P2B09GdjKzY084CM1yB",
   "stu:36:-P2B5Ooof8XaHcxcxOZT",
   "stu:37:-P2B3F63oAZMByik5EA-",
   "stu:3:-P2B-KB62XfTsw8GngWS",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "stu:47:-P2AzXCJUoZBWXYA1c2o",
   "stu:48:-P2BCDcUreQ4GJTnNPQF",
   "stu:50:-P2B4q3NOzFDEOb3W1vc",
   "stu:51:-P2B3QmzlTbuHdXrbzLy",
   "stu:64:-P2B0gVaTthJtyYsBrkG",
   "stu:7:-P2B37zH4wqV3dVP_NUJ",
   "team_diminish",
   "vampire",
   "whisper"
  ],
  "stu:42:-P2B85mmWk1Nz48l13eN": [
   "anonymous",
   "blitz",
   "chips_1",
   "chips_20",
   "comeback",
   "drain",
   "elements",
   "fog",
   "ghost",
   "guard",
   "items",
   "no_repeat",
   "redirect",
   "roles",
   "stu:10:-P2B0dmHkunxunTPekwO",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:13:-P2B5_V4r6MtzzRJ9NLe",
   "stu:18:-P2BBk1VRoxDEwd2tY5d",
   "stu:1:-P2B8ecngBuFVPbiwyEh",
   "stu:21:-P2AzhE_4Gm3CrTJ9N81",
   "stu:27:-P2B92Hu_rCT_8m3mrHF",
   "stu:29:-P2B97a2KWneHHRcSjGf",
   "stu:36:-P2B5Ooof8XaHcxcxOZT",
   "stu:37:-P2B3F63oAZMByik5EA-",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "stu:47:-P2AzXCJUoZBWXYA1c2o",
   "stu:48:-P2BCDcUreQ4GJTnNPQF",
   "stu:50:-P2B4q3NOzFDEOb3W1vc",
   "stu:51:-P2B3QmzlTbuHdXrbzLy",
   "stu:64:-P2B0gVaTthJtyYsBrkG",
   "stu:7:-P2B37zH4wqV3dVP_NUJ",
   "team_diminish",
   "vampire",
   "whisper"
  ],
  "stu:43:-P2B0Aei9XIYF0BSxi8e": [
   "chips_1",
   "elements",
   "fog"
  ],
  "stu:44:-P2B8HCd2cKi1btq7y7I": [
   "anonymous",
   "blitz",
   "chips_1",
   "chips_20",
   "comeback",
   "drain",
   "elements",
   "events",
   "fog",
   "ghost",
   "guard",
   "items",
   "no_repeat",
   "redirect",
   "roles",
   "round_cap",
   "stu:10:-P2B0dmHkunxunTPekwO",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:13:-P2B5_V4r6MtzzRJ9NLe",
   "stu:18:-P2BBk1VRoxDEwd2tY5d",
   "stu:1:-P2B8ecngBuFVPbiwyEh",
   "stu:21:-P2AzhE_4Gm3CrTJ9N81",
   "stu:27:-P2B92Hu_rCT_8m3mrHF",
   "stu:29:-P2B97a2KWneHHRcSjGf",
   "stu:31:-P2B09GdjKzY084CM1yB",
   "stu:36:-P2B5Ooof8XaHcxcxOZT",
   "stu:37:-P2B3F63oAZMByik5EA-",
   "stu:3:-P2B-KB62XfTsw8GngWS",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:47:-P2AzXCJUoZBWXYA1c2o",
   "stu:48:-P2BCDcUreQ4GJTnNPQF",
   "stu:50:-P2B4q3NOzFDEOb3W1vc",
   "stu:51:-P2B3QmzlTbuHdXrbzLy",
   "stu:64:-P2B0gVaTthJtyYsBrkG",
   "stu:7:-P2B37zH4wqV3dVP_NUJ",
   "team_diminish",
   "vampire",
   "whisper"
  ],
  "stu:46:-P2AzLdZx-Nd6vHLsyZH": [
   "chips_1",
   "fog",
   "round_cap"
  ],
  "stu:47:-P2AzXCJUoZBWXYA1c2o": [
   "anonymous",
   "blitz",
   "fog",
   "round_cap",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "whisper"
  ],
  "stu:48:-P2BCDcUreQ4GJTnNPQF": [
   "anonymous",
   "blitz",
   "chips_1",
   "fog",
   "round_cap",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "whisper"
  ],
  "stu:49:-P2B09-n5zf1Wudi7G24": [
   "fog",
   "round_cap"
  ],
  "stu:50:-P2B4q3NOzFDEOb3W1vc": [
   "anonymous",
   "blitz",
   "chips_1",
   "fog",
   "round_cap",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "whisper"
  ],
  "stu:51:-P2B3QmzlTbuHdXrbzLy": [
   "anonymous",
   "blitz",
   "chips_1",
   "fog",
   "round_cap",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "whisper"
  ],
  "stu:52:-P2B2keGRds5euNq7jDt": [
   "fog"
  ],
  "stu:53:-P2BAjffQXdJaIE5d2dg": [
   "chips_1",
   "fog"
  ],
  "stu:54:-P2B65xZ3SrtmoqcxJ3n": [
   "chips_1",
   "fog",
   "round_cap"
  ],
  "stu:5:-P2B8S5V5cot0tguquHo": [
   "chips_1",
   "chips_20",
   "fog",
   "round_cap"
  ],
  "stu:61:-P2BG3Pq0XolXI-rO6rU": [
   "chips_1",
   "fog"
  ],
  "stu:63:-P2B3clYH5CtTdSgk0DT": [
   "fog",
   "round_cap"
  ],
  "stu:64:-P2B0gVaTthJtyYsBrkG": [
   "anonymous",
   "blitz",
   "chips_1",
   "fog",
   "round_cap",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "whisper"
  ],
  "stu:6:-P2B5SZ7379YyLXx41-8": [
   "chips_1",
   "fog"
  ],
  "stu:7:-P2B37zH4wqV3dVP_NUJ": [
   "anonymous",
   "blitz",
   "chips_1",
   "fog",
   "round_cap",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "whisper"
  ],
  "team_diminish": [
   "anonymous",
   "blitz",
   "chips_1",
   "fog",
   "round_cap",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "timed_talk",
   "whisper"
  ],
  "team_hard": [
   "chips_1",
   "fog",
   "round_cap"
  ],
  "team_mob": [
   "fog"
  ],
  "team_penalty": [
   "anonymous",
   "chips_1",
   "fog",
   "ghost",
   "round_cap",
   "stack",
   "theme_mol",
   "whisper"
  ],
  "team_square": [
   "anonymous",
   "blitz",
   "chips_1",
   "fog",
   "round_cap"
  ],
  "theme_charm": [
   "chips_1",
   "fog",
   "round_cap"
  ],
  "theme_mol": [
   "chips_1",
   "decay",
   "defend_weak",
   "fog",
   "round_cap",
   "team_penalty"
  ],
  "theme_money": [
   "chips_1",
   "fog",
   "round_cap"
  ],
  "theme_office": [
   "chips_1",
   "fog",
   "round_cap"
  ],
  "timed_talk": [
   "anonymous",
   "blitz",
   "chips_1",
   "chips_20",
   "comeback",
   "drain",
   "elements",
   "events",
   "fog",
   "ghost",
   "guard",
   "items",
   "no_repeat",
   "redirect",
   "stu:3:-P2B-KB62XfTsw8GngWS",
   "team_diminish"
  ],
  "vampire": [
   "anonymous",
   "blitz",
   "fog",
   "round_cap",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "whisper"
  ],
  "whisper": [
   "anonymous",
   "blitz",
   "chips_1",
   "chips_20",
   "comeback",
   "decay",
   "defend_weak",
   "drain",
   "elements",
   "events",
   "fog",
   "ghost",
   "guard",
   "items",
   "no_repeat",
   "redirect",
   "round_cap",
   "stu:10:-P2B0dmHkunxunTPekwO",
   "stu:11:-P2BAe3ohZSRO5b-VhPv",
   "stu:12:-P2BAU97nHwtxxKcdNgU",
   "stu:13:-P2B5_V4r6MtzzRJ9NLe",
   "stu:18:-P2BBk1VRoxDEwd2tY5d",
   "stu:21:-P2AzhE_4Gm3CrTJ9N81",
   "stu:27:-P2B92Hu_rCT_8m3mrHF",
   "stu:29:-P2B97a2KWneHHRcSjGf",
   "stu:31:-P2B09GdjKzY084CM1yB",
   "stu:36:-P2B5Ooof8XaHcxcxOZT",
   "stu:37:-P2B3F63oAZMByik5EA-",
   "stu:3:-P2B-KB62XfTsw8GngWS",
   "stu:41:-P2B2G8cXTL02fSJhM3t",
   "stu:42:-P2B85mmWk1Nz48l13eN",
   "stu:44:-P2B8HCd2cKi1btq7y7I",
   "stu:47:-P2AzXCJUoZBWXYA1c2o",
   "stu:48:-P2BCDcUreQ4GJTnNPQF",
   "stu:50:-P2B4q3NOzFDEOb3W1vc",
   "stu:51:-P2B3QmzlTbuHdXrbzLy",
   "stu:64:-P2B0gVaTthJtyYsBrkG",
   "stu:7:-P2B37zH4wqV3dVP_NUJ",
   "team_diminish",
   "team_penalty",
   "vampire"
  ]
 },
 "note_20260923_persona": "改用會發言的 persona 測試員重跑之後：先前隨機出牌測不完的卡（fog/guard/theme_office）全部三場過關——那從來不是卡片的問題，是測試員不會社交。沉默的測試員測不出靠講話運作的功能，這個結論已經證實。",
 "note_20260923_final": "人工核定（自動腳本的粗糙分類已覆寫）：theme_charm/last_one 補測後排除嫌疑，回到已實測；draw_target 維持⚠（8場6過，機制可解釋但仍偶發）；range2需6人以上才有意義（設計如此，今晚測不到）；jury卡在R5是測試腳本沒做陪審團猜測介面、非卡片問題；factions在1v1殘局大概率跟last_one同一種限制（TEAM需2個攻擊者），但沒有重新用SOLO邏輯驗證過，如實列未確認，不宣稱已驗證。",
 "note_20260923_uipairs_bug": "2026-09-23 上課前總驗收抓到：uiPairs 從頭到尾是空的（之前只算給楊老師看數字，沒有真的寫回檔案），matesOf() 因此退回讀 mates（引擎層 755 組寬鬆清單），導致「🔗 可配」標籤顯示幾乎所有卡都能配，跟只有 20 組真正 UI 驗證過的事實完全不符。已修正為只用 uiPairs 這 20 組。另注意：13 張兩兩組合測試（234場）的 persona 發言數是 0——跟 40 張單卡測試不同，這批沒有真的驗證到需要協調講話才會出現的問題，20 組的可信度比單卡測試低。",
 "longPairs": [
  "anonymous|no_repeat",
  "anonymous|stu:13:-P2B5_V4r6MtzzRJ9NLe",
  "anonymous|stu:29:-P2B97a2KWneHHRcSjGf",
  "anonymous|stu:36:-P2B5Ooof8XaHcxcxOZT",
  "blitz|chips_20",
  "blitz|no_repeat",
  "blitz|stu:13:-P2B5_V4r6MtzzRJ9NLe",
  "blitz|stu:29:-P2B97a2KWneHHRcSjGf",
  "blitz|stu:36:-P2B5Ooof8XaHcxcxOZT",
  "chips_20|drain",
  "chips_20|fog",
  "chips_20|last_one",
  "chips_20|stu:11:-P2BAe3ohZSRO5b-VhPv",
  "chips_20|stu:12:-P2BAU97nHwtxxKcdNgU",
  "chips_20|stu:14:-P2B9I9gGwDYhIvnvASd",
  "chips_20|stu:41:-P2B2G8cXTL02fSJhM3t",
  "chips_20|stu:42:-P2B85mmWk1Nz48l13eN",
  "chips_20|stu:44:-P2B8HCd2cKi1btq7y7I",
  "chips_20|stu:5:-P2B8S5V5cot0tguquHo",
  "chips_20|timed_talk",
  "chips_20|whisper",
  "fog|last_one",
  "fog|no_repeat",
  "fog|stu:13:-P2B5_V4r6MtzzRJ9NLe",
  "fog|stu:14:-P2B9I9gGwDYhIvnvASd",
  "fog|stu:36:-P2B5Ooof8XaHcxcxOZT",
  "fog|stu:5:-P2B8S5V5cot0tguquHo",
  "no_repeat|stu:11:-P2BAe3ohZSRO5b-VhPv",
  "no_repeat|stu:12:-P2BAU97nHwtxxKcdNgU",
  "no_repeat|stu:41:-P2B2G8cXTL02fSJhM3t",
  "no_repeat|stu:42:-P2B85mmWk1Nz48l13eN",
  "no_repeat|stu:44:-P2B8HCd2cKi1btq7y7I",
  "no_repeat|timed_talk",
  "no_repeat|whisper",
  "stu:11:-P2BAe3ohZSRO5b-VhPv|stu:13:-P2B5_V4r6MtzzRJ9NLe",
  "stu:11:-P2BAe3ohZSRO5b-VhPv|stu:29:-P2B97a2KWneHHRcSjGf",
  "stu:11:-P2BAe3ohZSRO5b-VhPv|stu:36:-P2B5Ooof8XaHcxcxOZT",
  "stu:12:-P2BAU97nHwtxxKcdNgU|stu:13:-P2B5_V4r6MtzzRJ9NLe",
  "stu:12:-P2BAU97nHwtxxKcdNgU|stu:29:-P2B97a2KWneHHRcSjGf",
  "stu:12:-P2BAU97nHwtxxKcdNgU|stu:36:-P2B5Ooof8XaHcxcxOZT",
  "stu:13:-P2B5_V4r6MtzzRJ9NLe|stu:41:-P2B2G8cXTL02fSJhM3t",
  "stu:13:-P2B5_V4r6MtzzRJ9NLe|stu:42:-P2B85mmWk1Nz48l13eN",
  "stu:13:-P2B5_V4r6MtzzRJ9NLe|stu:44:-P2B8HCd2cKi1btq7y7I",
  "stu:13:-P2B5_V4r6MtzzRJ9NLe|whisper",
  "stu:29:-P2B97a2KWneHHRcSjGf|stu:41:-P2B2G8cXTL02fSJhM3t",
  "stu:29:-P2B97a2KWneHHRcSjGf|stu:42:-P2B85mmWk1Nz48l13eN",
  "stu:29:-P2B97a2KWneHHRcSjGf|stu:44:-P2B8HCd2cKi1btq7y7I",
  "stu:29:-P2B97a2KWneHHRcSjGf|whisper",
  "stu:36:-P2B5Ooof8XaHcxcxOZT|stu:41:-P2B2G8cXTL02fSJhM3t",
  "stu:36:-P2B5Ooof8XaHcxcxOZT|stu:42:-P2B85mmWk1Nz48l13eN",
  "stu:36:-P2B5Ooof8XaHcxcxOZT|stu:44:-P2B8HCd2cKi1btq7y7I",
  "stu:36:-P2B5Ooof8XaHcxcxOZT|whisper"
 ],
 "note_20260923_uipairs_expand": "2026-09-23 晚：兩張組合 480 組 × 3 輪（三種玩家組成）介面實測後放寬。三輪都 ✅ 的開放；有 🟡（機器人 15 回合打不完、但沒卡住）的也開放，選到時標「對局會比較長」（longPairs）；有 🟠（要 GM 強制結算）的 13 組不開。原有 20 組 → 現在 484 組。"
};
